### ISSUE TITLE
Adopt and use GSA digital tools and services

### ISSUE THREAD

**Issue by RachelF** [GSA/wg-web-modernization#28]
# Story

As a website manager
I want to see a list of all GSA digital tools and services I could implement on my site
So that I can identify those which could save money and/or improve DX

# Acceptance Criteria

Given that GSA maintains a central list digital tools and services
When site managers review it
Then they can find guidance on how to implement any tool on the list 

###### Related issues
https://github.com/GSA/wg-web-modernization/issues/21

**Comment by ryanwoldatwork** [comment]
Hi @RachelF, is https://digital.gov/services sufficient?

**Comment by RachelF** [comment]
yes I think so
