### ISSUE TITLE
Website Evaluations

### ISSUE THREAD

**Issue by RachelF** [GSA/wg-web-modernization#49]
# Website Evaluation Process
Every three years, all GSA websites will be reviewed for adherence to a small set of criteria intended to provide indicators as to the overall health, management, and compliance of the site to federal web policy.

The EDX Team in OCE will meet with website managers to conduct these reviews, and provide a report of their findings. 1/3 of GSA sites will be reviewed each year, and site managers will be notified when their site is up for review. EDX Team will develop criteria and a testing schedule.

# User Stories
As an EDX Team member
I want to understand the health of a GSA web property
So I can provide assistance to the web manager if they need it

As a website manager
I want to understand whether my site is operating in compliance with federal web policy and web best practices
So that I deliver a good experience to users

# Acceptance Criteria
Given a website is reviewed by EDX
When the website manager receives the findings report
Then the site manager will review the report and take any corrective actions needed

**Comment by ryanwoldatwork** [comment]
hi @RachelF,

just checking in on the status of the web evaluations,
and
should this issue live here, or in https://github.com/GSA/EDX/issues?

**Comment by ryanwoldatwork** [comment]
Hi @RachelF - can you take a look at this within the next week or so?

Is this still valid? Or, might this be more of an EDX issue?

**Comment by RachelF** [comment]
This is an EDX issue... and we have lots of tracking issues for this work in our EDX repo, so I will close this w/a referral to our [EDX repo](https://github.com/GSA/EDX). Thanks @ryanwoldatwork !
